lang: da

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Copenhagen

title: "GD8 Fødselsdage"

url: "https://eo-le.github.io/GD8"
baseurl: "" # only use if the jekyll project is in a subfolder

# layouts applied to different type of paths. If type is omitted then root directory is applied
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
