lang: da

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Copenhagen

# last_commit: "{{ site.time | date: '%Y-%m-%d %H:%M:%S' }}"

title: "Jekyll Actions Demo"

url: "https://eo-le.github.io/GD8/"
baseurl: ""

# layouts applied to different type of paths. If type is omitted then root directory is applied
defaults:
  - scope:
      path: ""
    values:
      layout: "default"



