lang: da

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Copenhagen

title: "GD8 Fødselsdage"

url: "https://gd8.dk"
baseurl: "" # only use if the jekyll project is in a subfolder

# layouts applied to different type of paths. If type is omitted then root directory is applied
defaults:
  - scope:
      path: ""
    values:
      layout: "default"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _data