lang: da-DK

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Europe/Copenhagen

title: "GD8 Fødselsdage"

url: "https://gd8.dk"
baseurl: "" # only use if the jekyll project is in a subfolder

collections:
  bills:
    output: true
  persons:
    output: true
  events:
    output: true


# layouts applied to different type of paths.
defaults:

  # if pages in folder _costs then use layout: cost.
  - scope:
      path: ""
      type: "bills"
    values:
      layout: "bill"

  # if pages in folder _persons then use layout: person.
  - scope:
      path: ""
      type: "persons"
    values:
      layout: "person"

  # if pages in folder _events then use layout: event.
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  
  # If type is omitted then root directory is applied
  - scope:
      path: ""
    values:
      layout: "default"



#plugins:
#  - jekyll-feed
  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
