name: Jekyll.yml Test

on:
  push:
    branches:
      - fixPersonsCollection
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Jekyll Command
        run: echo "Jekyll workflow test"
